-- Criação da tabela
CREATE TABLE t_mtf_operador
(
    cd_id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_operador    VARCHAR(120) NOT NULL,
    ds_senha       VARCHAR(255) NOT NULL,
    nm_role        VARCHAR(255) NOT NULL,
    cd_id_patio    INTEGER      NOT NULL
);

INSERT INTO t_mtf_operador (nm_operador, ds_senha, nm_role, cd_id_patio)
VALUES ('João Silva', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 1),
       ('Maria Oliveira', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 2),
       ('Carlos Pereira', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 3),
       ('Ana Costa', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 4),
       ('Roberto Almeida', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 5),
       ('Joao Almeida', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 1),
       ('Joao Almeida', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 1),
       ('ADMIN GERAL', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'ADMIN', 1),
       ('Joao Carlos', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 1),
       ('Joao Jota', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 1),
       ('Joao Almeida', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 1),
       ('Arthur Spedine', '$2a$12$728xWF5x0WXEaXQgTD7rRuVhDfKdhfmecrCzwqtp6htBQLS0mtxKS', 'OPERADOR', 1);

-- Constraint de chave estrangeira
ALTER TABLE t_mtf_operador
    ADD CONSTRAINT fk_operador_patio FOREIGN KEY (cd_id_patio)
        REFERENCES t_mtf_patio (cd_id_patio);
