-- Criação da tabela
CREATE TABLE t_mtf_moto (
    cd_id_moto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tipo VARCHAR(30) NOT NULL,
    nr_ano INT NOT NULL,
    nr_placa VARCHAR(7) UNIQUE,
    nr_preco_aluguel DECIMAL(8,2),
    fl_alugada CHAR(1) CHECK (fl_alugada IN ('S', 'N')) NOT NULL,
    dt_alocacao TIMESTAMP,
    nr_cod_rastreador INTEGER UNIQUE NOT NULL,
    dt_entrada TIMESTAMP,
    cd_id_setor INTEGER,
    CONSTRAINT fk_moto_setor FOREIGN KEY (cd_id_setor)
        REFERENCES t_mtf_setor_patio (cd_id_setor)
);



-- Criação do índice único
CREATE UNIQUE INDEX sys_c004910758 ON t_mtf_moto (cd_id_moto);
