-- Criação da tabela
CREATE TABLE t_mtf_endereco (
    cd_id_endereco INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_logradouro VARCHAR(255) NOT NULL,
    nr_endereco INTEGER,
    nm_bairro VARCHAR(255),
    nm_cidade VARCHAR(255) NOT NULL,
    sg_estado VARCHAR(255),
    nr_cep VARCHAR(255) NOT NULL
);

-- Inserção de dados
INSERT INTO t_mtf_endereco (nm_logradouro, nr_endereco, nm_bairro, nm_cidade, sg_estado, nr_cep) VALUES
('Avenida Paulista', 1000, 'Bela Vista', 'São Paulo', 'SP', '01310-100'),
('Rua dos Três Irmãos', 250, 'Vila Progredior', 'Rio de Janeiro', 'RJ', '22241-030'),
('Rua dos Eucaliptos', 500, 'Alphaville', 'Barueri', 'SP', '06474-080'),
('Rua Fagundes Filho', 650, 'Vila Independência', 'São Paulo', 'SP', '04283-000'),
('Rua Rio do Ouro', 325, 'Jardim Acapulco', 'Guarulhos', 'SP', '07084-010');
