-- Criação da tabela
CREATE TABLE t_mtf_patio (
    cd_id_patio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_apelido_patio VARCHAR(255) NOT NULL,
    nr_capacidade INTEGER NOT NULL,
    nr_area NUMERIC,
    cd_id_endereco INTEGER NOT NULL,
    UNIQUE (cd_id_endereco)
);

-- Inserção de dados
INSERT INTO t_mtf_patio (nm_apelido_patio, nr_capacidade, nr_area, cd_id_endereco) VALUES
('Pátio A', 50, 200, 1),
('Pátio B', 100, 500, 2),
('Pátio C', 75, 300, 3),
('Pátio D', 40, 150, 4),
('Pátio E', 60, 350, 5);

-- Constraint de chave estrangeira
ALTER TABLE t_mtf_patio
ADD CONSTRAINT fk_patio_endereco FOREIGN KEY (cd_id_endereco)
REFERENCES t_mtf_endereco (cd_id_endereco);
