-- Criação da tabela
CREATE TABLE t_mtf_patio (
    cd_id_patio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_apelido_patio VARCHAR(255),
    nr_capacidade INTEGER,
    nr_area NUMERIC,
    cd_id_endereco INTEGER NOT NULL,
    UNIQUE (cd_id_endereco)
);

-- Inserção de dados
INSERT INTO t_mtf_patio (cd_id_patio, nm_apelido_patio, nr_capacidade, nr_area, cd_id_endereco) VALUES
(1, 'Pátio A', 50, 200, 1),
(2, 'Pátio B', 100, 500, 2),
(3, 'Pátio C', 75, 300, 3),
(4, 'Pátio D', 40, 150, 4),
(5, 'Pátio E', 60, 350, 5);

-- Constraint de chave estrangeira
ALTER TABLE t_mtf_patio
ADD CONSTRAINT fk_patio_endereco FOREIGN KEY (cd_id_endereco)
REFERENCES t_mtf_endereco (cd_id_endereco);
