-- Criação da tabela
CREATE TABLE t_mtf_operador (
    cd_id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_operador VARCHAR(120) NOT NULL,
    ds_senha VARCHAR(255) NOT NULL,
    cd_id_patio INTEGER NOT NULL
);

-- Inserção de dados
INSERT INTO t_mtf_operador (cd_id_registro, nm_operador, ds_senha, cd_id_patio) VALUES
(1, 'João Silva', 'senha123', 1),
(2, 'Maria Oliveira', 'senha456', 2),
(3, 'Carlos Pereira', 'senha789', 3),
(4, 'Ana Costa', 'senha012', 4),
(5, 'Roberto Almeida', 'senha345', 5),
(83, 'Joao Almeida', '$2a$10$.tJzLbXrP2eG4gX9YTRWYum0iFICuDFbNUSAcuVjPbJP/bn07iWzm', 1),
(84, 'Joao Almeida', '$2a$10$iqaIYVvdub1r7DfrMfQoOOHcObpdeJCEe43pQpimwVZRd5nDn5GRe', 1),
(86, 'Joao Almeida', '$2a$10$.Hfd5Vp05fcMLBKvXbuV7O9qA9oZtouvytdOZFTNKAcfKO.ZUyLEu', 1),
(81, 'Joao Carlos', '$2a$10$YG4BaBNUL.cc.79YxBW87OYxz5mw.Dzi3QNqKrEYKZbUmjcbX0g8S', 1),
(87, 'Joao Jota', '$2a$10$txXO30XHDRktKGdpsvV5veQbINpXjNtIZl2vxCBbIjuNHloNX.aOe', 1),
(82, 'Joao Almeida', '$2a$10$Wfd2Rl52VcDk/cA3ICUIrumBZDMPY8URB1JhhEt1FDf83W5I5s2rG', 1),
(61, 'Arthur Spedine', '12346', 1);

-- Constraint de chave estrangeira
ALTER TABLE t_mtf_operador
ADD CONSTRAINT fk_operador_patio FOREIGN KEY (cd_id_patio)
REFERENCES t_mtf_patio (cd_id_patio);