-- Criação da tabela
CREATE TABLE t_mtf_posicao_patio (
    cd_id_posicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_posicao_vertical INTEGER NOT NULL,
    nr_posicao_horizontal VARCHAR(5) NOT NULL,
    fl_posicao_livre CHAR(1) NOT NULL,
    cd_id_patio INTEGER NOT NULL,
    cd_id_moto INTEGER,

    CONSTRAINT fk_posicao_patio FOREIGN KEY (cd_id_patio)
        REFERENCES t_mtf_patio (cd_id_patio),

    CONSTRAINT fk_posicao_moto FOREIGN KEY (cd_id_moto)
        REFERENCES t_mtf_moto (cd_id_moto),

    CONSTRAINT uq_posicao_moto UNIQUE (cd_id_moto)
);


