-- Criação da tabela
CREATE TABLE t_mtf_setor_patio (
    cd_id_setor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_setor VARCHAR(5) NOT NULL,
    nr_capacidade_setor INT NOT NULL,
    fl_posicao_livre CHAR(1) NOT NULL,
    cd_id_patio INTEGER NOT NULL,

    CONSTRAINT fk_setor_patio FOREIGN KEY (cd_id_patio)
        REFERENCES t_mtf_patio (cd_id_patio)
);

