
INSERT INTO t_mtf_posicao_patio (
    nr_posicao_vertical, nr_posicao_horizontal, fl_posicao_livre,
    cd_id_patio, cd_id_moto
) VALUES
(1, 'A', 'S', 1, NULL),
(2, 'B', 'N', 2, 2),
(4, 'D', 'N', 4, 4),
(5, 'E', 'S', 5, NULL),
( 2, 'A', 'S', 1, NULL),
( 3, 'A', 'S', 1, NULL),
( 4, 'A', 'S', 1, NULL),
( 5, 'A', 'S', 1, NULL),
( 6, 'A', 'S', 1, NULL),
( 7, 'A', 'S', 1, NULL),
( 8, 'A', 'S', 1, NULL),
( 9, 'A', 'S', 1, NULL),
( 10, 'A', 'S', 1, NULL),
( 1, 'B', 'S', 1, NULL),
( 3, 'B', 'S', 1, NULL),
( 2, 'A', 'S', 2, NULL),
( 4, 'B', 'S', 1, NULL),
( 5, 'B', 'S', 1, NULL),
( 6, 'B', 'S', 1, NULL),
( 7, 'B', 'S', 1, NULL),
( 8, 'B', 'S', 1, NULL),
( 9, 'B', 'S', 1, NULL),
( 10, 'B', 'S', 1, NULL),
( 1, 'C', 'S', 1, NULL),
( 3, 'C', 'S', 1, NULL),
( 2, 'C', 'S', 1, NULL),
( 4, 'C', 'S', 1, NULL),
( 5, 'C', 'S', 1, NULL),
( 6, 'C', 'S', 1, NULL),
( 7, 'C', 'S', 1, NULL),
( 8, 'C', 'S', 1, NULL),
( 9, 'C', 'S', 1, NULL),
( 10, 'C', 'S', 1, NULL);
